api:
  deployment:
    replicaCount: 1
    image: api:latest
  service:
    type: NodePort 
    port: 8000

frontend:
  deployment:
    replicaCount: 1
    image: frontend:latest
  service:
    type: NodePort 
    port: 9000

redis:
  deployment:
    replicaCount: 1
    image: redis:latest
  service:
    type: NodePort
    port: 6379

storage:
  class: docker-sc
  localEnabled: true
  localPath: "/Users/adamtaylor/data"

# Leftovers
ingress:
  class: nginx
  host: localhost

