apiVersion: v1
kind: Service
metadata:
  name: api 
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app: api 
  ports:
    - protocol: TCP
      port: {{ .Values.api.service.port }} 
      targetPort: {{ .Values.api.service.port }}

