apiVersion: v1
kind: Service
metadata:
  name: redis 
spec:
  type: {{ .Values.redis.service.type }}
  selector:
    app: redis 
  ports:
    - protocol: TCP
      port: {{ .Values.redis.service.port }} 
      targetPort: {{ .Values.redis.service.port }}

